config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  
  get 'users/new'

  root 'static_pages#home'
  
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'uit_projects' => 'static_pages#uit_projects'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
  		format: { with: VALID_EMAIL_REGEX },
  		uniqueness: { case_sensitive: false }
  validates :password, presence:true, length: { minimum:6 }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Welcome to the sample app!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

	private
	  def user_params
	  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis (with no leader if no title is provided)
	def full_title(page_title = '')
		base_title = "Cosmic Conversations"
		if page_title.empty?
			base_title
		else
			page_title + ' | ' + base_title
		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "responsive-img circle")
	end
end

app/views/layouts/_footer.html.erb
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Seonaid Lee, M.Sc., B.Ed., PDC</h5>
          <p class="grey-text text-lighten-4">Available for complex thought form wrestling. Meditation instruction, technical specifications, web development, and custom word art.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li> <a href="https://twitter.com/seonaid_lee" target = "_blank" class="grey-text text-lighten-3">Twitter</a></li>
            <li> <a href="https://instagram.com/seonaid_lee/" target = "_blank" class="grey-text text-lighten-3">Instagram</a></li>
            <li> <a href="https://ca.linkedin.com/pub/seonaid-lee/95/7b7/33a" target = "_blank" class="grey-text text-lighten-3">LinkedIn</a></li>
<!--             <li><%= link_to "Contact", contact_path, class: "grey-text text-lighten-3" %></li> -->
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2015 Seonaid Lee
<!--      <a class="grey-text text-lighten-4 right" href="#!">More Links</a> -->
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <nav class = "teal darken-1">
    <div class="container">
    <div class="nav-wrapper">
  		<%= link_to " Seonaid Lee", root_path, id: "logo", class: "brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
				<li><%= link_to "Home", root_path %></li>
<!-- 				<li><%= link_to "Help", help_path %></li> -->
				<li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
				<li><%= link_to "Home", root_path %></li>
<!-- 				<li><%= link_to "Help", help_path %></li> -->
				<li><%= link_to "About", about_path %></li>
      </ul>
    </div></div>
  </nav>
</header>

app/views/layouts/_leftnav.html.erb
      <div class="collection">
        <%= link_to "Home", root_path, class: "collection-item" %>
        <%= link_to "UIT Projects", uit_projects_path, class: "collection-item" %>

        <a href="#!" class="collection-item">Business Analysis</a>
        <a href="#!" class="collection-item">Writing</a>
        <a href="#!" class="collection-item">Instructional Design</a>
      </div>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
 
     <main> 
      <div class="container">
        <div class="row">
      <div class="col s12">
<!--         <div class="row">
        <div class="col s6 m3">
          <%= render 'layouts/leftnav' %>
        </div> -->

<!--         <div class="col s9"> -->
<!-- <div class="container"> -->
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>      
          <%= yield %>
        </div></div>
<!--       </div> -->
<!-- </div> -->
        </div>
      </div>    
    </main>
    
    <div class="container"><%= debug(params) if Rails.env.development? %> </div>    
    <%= render 'layouts/footer' %>

  </body>
</html>

<script type="text/javascript">$(".button-collapse").sideNav();</script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h3>About Me</h3>

<div class="card z-depth-3">
  <div class="card-content white-text">
    <div class="row">
    <div class="col m4">
      <a class="twitter-timeline" href="https://twitter.com/seonaid_lee" data-widget-id="605421579892322305">Tweets by @seonaid_lee</a>
      
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      </script>
      
    </div>  
    <div class="col m8">
      <div class="card-panel grey lighten-5 z-depth-1">
        <div class="row valign-wrapper">

          <div class="col m12">
            <div class="row">         
              <div class="col m3">
                <%= image_tag "Headshot-me.jpg", class: "circle responsive-img" %>
              </div>            
          <span class = "black-text art-text">

Seonaid Lee is a physicist turned sociologist who has previously worked as a software developer, a technical writer, and a curriculum developer. She is currently completing a tech entrepreneurship program and seeking new challenges. She is also a prolific blogger.
            </span></div>


                    <div class="row">
        <div class="col m6">
          <!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://figuresthingsout.com/rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
        </div>
        <div class="col m6">
            <!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://thepracticaldilettante.com/rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
          </div>

        </div>

        <div class="row"> 
            <div class="col m6">
              <!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://mappingtheuniverse.wordpress.com/?rss",rssmikle_frame_width: "300",rssmikle_frame_height: "400",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "12",rssmikle_border: "on",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "on",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M:%S %p",item_description_style: "text+tn",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; "><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!-- end feedwind code -->
            </div>
        </div>
          </div>

        </div>
      

</div>
      </div>
    </div>
  </div>
</div>

  

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

	<h1>Contact</h1>

	<p>I got email. I got twitter. I got The Facebook. I got Instagram. I'm all over this contact thing.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
I am going to be a help page. i wll be helpful.

app/views/static_pages/home.html.erb
<h2>UIT Projects</h2>
    
      <div class="row">
        <div class="col s12 m6 l4">
          <div class="card large">
            <div class="card-image">
              <%= image_tag "RailsProject.png", class: "responsive-img", alt: "screenshot of project" %>
            </div>
            <div class="card-content">
              <h5 class="black-text">Simple eCommerce Site</h5>
              <ul>
                <li>Ruby on Rails</li>
                <li>Devise</li>
                <li>Active Admin</li>
                <li>Stripe Integration</li>
                <li>SumoMe</li>

                <li><h6>Repo available on BitBucket</h6></li>
                <li><a href="https://youtu.be/cZklUF501ec?t=8m20s" target="_blank">Presentation about Rails</a> </li>
                <br>                
                <li>With great thanks to Leo Trieu at <a href="https://code4startup.com/">Code4Startup</a> !</li>
              </ul>

            </div>
<!--             <div class="card-action">
              <a href="http://45.55.66.13" target="_blank">Demonstration Site</a>
            </div> -->
          </div>
        </div>

        <div class="col s12 m6 l4">
          <div class="card large">
            <div class="card-image">
              <%= image_tag "UseThis.png", class: "responsive-img", alt: "Picture of a peacock" %>
            </div>
            <div class="card-content">
              <h5 class="black-text">UseThis!</h5>            
              <p>Perishable food tracking mobile app with simplified meal planning</p>
              <ul>
                <li>NodeJS with Express back end</li>
                <li>REST API</li>
                <li>Ionic mobile app</li>
                <li>XCode prototyping</li>
                <li>Sketch</li>
                <li><a href="https://github.com/Seonaid/UseThisFront" target="_blank">Front End Github Repo</a></li>                
                <li><a href="https://github.com/Seonaid/UseThisBack" target="_blank">Back End Github Repo</a></li>
                <li><a href="https://www.youtube.com/watch?v=CqOf6Noc3pw&feature=youtu.be&t=15m51s" target="_blank">UseThis Pitch with Demo</a></li>
              </ul>
            </div>
            <div class="card-action">
              <a href="http://104.236.37.141/register" target="_blank">Demonstration Site</a>
            </div>
          </div>
        </div>

        <div class="col s12 m6 l4">
          <div class="card large">
            <div class="card-image">
              <%= image_tag "NodePlusExpress.png", class: "responsive-img", alt: "Screenshot of programming project" %>
<!--               <span class="card-title">Social Network</span>
 -->            </div>
            <div class="card-content">
              <h5 class="black-text">Social Network</h5>   
              <p>Design and prototype for a community-based social network. <br>
                Stack:
                <ul> 
                  <li>Ubuntu 14.01</li>
                  <li>NodeJS / Express</li>
                  <li>Postgres</li>
                  <li>Sequelize (ORM) </li>
                  <li>Jade Templating engine</li>
                  <li>Bootstrap</li>
                  <li><a href="https://github.com/Seonaid/social_network" target="_blank">Github Repo</a> </li>
                  <li><a href="https://www.youtube.com/watch?v=kbk1aJQyLXM" target="_blank">Presentation on Nerdique Goals</a> </li>
                </ul></p>
            </div>
<!--             <div class="card-action">
              <a href="http://104.236.57.202/" target="_blank">Demonstration Site</a>
            </div> -->
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12 m6 l4">
          <div class="card large" style= "height: 500px">
            <div class="card-image">
              <%= image_tag "GhostBlog.png", class: "responsive-img", alt: "Screenshot of programming project" %>
              <!-- <span class="card-title">Ghost Blog</span> -->
            </div>
            <div class="card-content">
              <h5 class="black-text">Ghost Blog</h5>   

              <p>Installation and deployment of Ghost</p>
              <ul>
                <li>Digital Ocean</li>
                <li>Cloud Flare</li>
                <li>NodeJS</li>
                <li>Ghost</li>
                <li>Year long blog on learning outcomes</li>
              </ul>
            </div>
            <div class="card-action">
              <a href="http://figuresthingsout.com" target="_blank">FiguresThingsOut.com</a>
            </div>
          </div>
        </div>

        <div class="col s12 m6 l4">
          <div class="card large" style= "height: 500px">
            <div class="card-image">
              <%= image_tag "ChatApp.png", class: "responsive-img", alt: "Picture of a peacock" %>
              <!-- <span class="card-title grey-text text-darken-3">Chat Application</span> -->
            </div>
            <div class="card-content">
              <h5 class="black-text">Chat Application</h5>
              <ul>
                <li>NodeJS</li>
                <li>socket.io</li>
                <li>Redis</li>
                <li>BCrypt password encryption</li>
                <li>CSS migrated from Ghost Blog</li>
                <li><a href="https://github.com/Seonaid/simple-chat-server" target="_blank">Github Repo</a> </li>
                <li><a href="https://www.youtube.com/watch?v=R1nU7mLrchU" target="_blank">Presentation on User Authentication</a> </li>

              </ul>

            </div>
<!--             <div class="card-action">
              <a href="http://104.131.67.121/" target="_blank">Friendly Chat</a>
            </div> -->
          </div>
        </div>

        <div class="col s12 m6 l4">
          <div class="card large" style= "height: 500px">
            <div class="card-image">
              <%= image_tag "board_game.jpg", class: "responsive-img", alt: "Picture of a peacock" %>
              <!-- <span class="card-title">Nerdique - Website</span> -->
            </div>
            <div class="card-content">
              <h5 class="black-text">Nerdique - Website</h5>
              <p>Marketing website and strategies for social network project.</p>
              <p>Copywriting</p>
              <p>Deploying Wordpress</p>
              <p>Follow us on <a href="http://twitter.com/nerdique" target="_blank">Twitter</a></p>
            </div>
            <div class="card-action">
              <a href="http://nerdique.com" target="_blank">Nerdique.com</a>
            </div>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col s12 m6 l4">
          <div class="card large" style= "height: 500px">
            <div class="card-image">
              <%= image_tag "AngularProject.png", class: "responsive-img", alt: "Picture of a peacock" %>
            </div>
            <div class="card-content">
              <h5 class="black-text">Exchange Marketplace</h5>
              <ul>
                <li>Angular</li>
                <li>Firebase</li>
                <li>Bootstrap</li>
                <li><a href="https://github.com/Seonaid/Seonaid.github.io" target="_blank">Github Repo</a> </li>
                <li><a href="https://www.youtube.com/watch?v=HtMK5r-wnwk" target="_blank">Presentation on what constitutes MVP</a> </li>
                <br>                
                <li>With great thanks to Leo Trieu at <a href="https://code4startup.com/">Code4Startup</a> !</li>
              </ul>

            </div>
            <div class="card-action">
              <a href="https://seonaid.github.io/#/" target="_blank">GitHub Pages</a>
            </div>
          </div>
        </div>
      </div>

app/views/static_pages/uit_projects.html.erb
<h2>UIT Projects</h2>
    
      <div class="row">
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <%= image_tag "NodePlusExpress.png", class: "responsive-img", alt: "Screenshot of programming project" %>
              <span class="card-title">Social Network</span>
            </div>
            <div class="card-content">
              <p>Desgin and prototype for a community-based social network.
                Stack:
                <ul> 
                  <li>Ubuntu 14.01</li>
                  <li>NodeJS / Express</li>
                  <li>Postgres</li>
                  <li>Jade Templating engine</li>
                  <li>Bootstrap</li>
                </ul></p>
            </div>
            <div class="card-action">
              <a href="http://104.236.57.202/" target="_blank">Demonstration Site</a>
            </div>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <%= image_tag "board_game.jpg", class: "responsive-img", alt: "Picture of a peacock" %>
              <span class="card-title">Nerdique - Website</span>
            </div>
            <div class="card-content">
              <p>Preliminary content generation and marketing strategies for social network.</p>
            </div>
            <div class="card-action">
              <a href="http://nerdique.com" target="_blank">Nerdique.com</a>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <%= image_tag "ChatApp.png", class: "responsive-img", alt: "Picture of a peacock" %>
              <span class="card-title grey-text">Chat Application</span>
            </div>
            <div class="card-content">
              <ul>
                <li>NodeJS</li>
                <li>socket.io</li>
                <li>Redis</li>
                <li>BCrypt password encryption</li>
                <li>CSS migrated from Ghost Blog</li>
                <li><a href="https://github.com/Seonaid/simple-chat-server" target="_blank">Github Repo</a> </li>
                <li><a href="https://www.youtube.com/watch?v=R1nU7mLrchU" target="_blank">Presentation on User Authentication</a> </li>

              </ul>

            </div>
            <div class="card-action">
              <a href="http://104.131.67.121/" target="_blank">Friendly Chat</a>
            </div>
          </div>
        </div>
      </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign Up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			<div class="input-field col s12">
	      <%= f.text_field :name, :class => "validate", :placeholder => "Name" %>
			</div>
			<div class="input-field col s12">      
	      <%= f.email_field :email, :class => "validate", :placeholder => "email" %>
			</div>
			<div class="input-field col s12">  
	      <%= f.password_field :password, :class => "validate", :placeholder => "Password"   %>
			</div>
			<div class="input-field col s12">  
	      <%= f.password_field :password_confirmation, :class => "validate", :placeholder => "Confirm Password"   %>
			</div>
 
	      <%= f.submit "Create my account", class: "btn" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>